#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR="${1:-${REPO_DIR}/../wallets/mainnet-test}"
NETWORK="${NETWORK:-bitcoin}"

HRMW() {
  (cd "${REPO_DIR}" && cargo run --quiet --bin hrmw -- "$@")
}

wallet_field() {
  local wallet_path="$1"
  local key="$2"
  local out
  out="$(HRMW --wallet "${wallet_path}" info)"
  awk -F': ' -v k="${key}" '$1 ~ k { print $2; exit }' <<<"${out}"
}

create_wallet() {
  local name="$1"
  local wallet_dir="${OUT_DIR}/${name}"
  local wallet_db="${wallet_dir}/master.db"
  mkdir -p "${wallet_dir}"

  if [[ ! -f "${wallet_db}" ]]; then
    echo "[${name}] creating wallet ${wallet_db}"
    HRMW --wallet "${wallet_db}" setup >/dev/null
  else
    echo "[${name}] wallet already exists: ${wallet_db}"
  fi

  local mnemonic
  mnemonic="$(HRMW --wallet "${wallet_db}" key export --format mnemonic)"
  printf '%s\n' "${mnemonic}" > "${wallet_dir}/mnemonic.txt"
  chmod 600 "${wallet_dir}/mnemonic.txt"

  local sidecar="${wallet_db}.recovery.txt"
  if [[ -f "${sidecar}" ]]; then
    cp -f "${sidecar}" "${wallet_dir}/recovery.txt"
    chmod 600 "${wallet_dir}/recovery.txt"
  fi

  local fp taproot board offchain
  fp="$(wallet_field "${wallet_db}" "RGB fingerprint")"
  taproot="$(HRMW --wallet "${wallet_db}" bitcoin address --network "${NETWORK}" --kind taproot --index 0)"
  board="$(HRMW --wallet "${wallet_db}" bitcoin ark board --network "${NETWORK}")"
  offchain="$(HRMW --wallet "${wallet_db}" bitcoin ark offchain --network "${NETWORK}")"

  cat > "${wallet_dir}/summary.txt" <<EOF
name=${name}
wallet_db=${wallet_db}
fingerprint=${fp}
taproot_index0=${taproot}
ark_boarding_address=${board}
ark_offchain_address=${offchain}
EOF

  echo "[${name}] fingerprint: ${fp}"
  echo "[${name}] taproot[0]: ${taproot}"
  echo "[${name}] ARK board: ${board}"
}

verify_recovery() {
  local name="$1"
  local wallet_dir="${OUT_DIR}/${name}"
  local wallet_db="${wallet_dir}/master.db"
  local mnemonic_file="${wallet_dir}/mnemonic.txt"
  local rec_dir="${OUT_DIR}/${name}-recovered"
  local rec_db="${rec_dir}/master.db"

  if [[ ! -f "${mnemonic_file}" ]]; then
    echo "[${name}] missing mnemonic file ${mnemonic_file}" >&2
    return 1
  fi

  rm -rf "${rec_dir}"
  mkdir -p "${rec_dir}"
  HRMW --wallet "${rec_db}" setup >/dev/null
  HRMW --wallet "${rec_db}" key import --mnemonic "$(cat "${mnemonic_file}")" --force >/dev/null

  local a_fp b_fp a_tap b_tap a_board b_board
  a_fp="$(wallet_field "${wallet_db}" "RGB fingerprint")"
  b_fp="$(wallet_field "${rec_db}" "RGB fingerprint")"
  a_tap="$(HRMW --wallet "${wallet_db}" bitcoin address --network "${NETWORK}" --kind taproot --index 0)"
  b_tap="$(HRMW --wallet "${rec_db}" bitcoin address --network "${NETWORK}" --kind taproot --index 0)"
  a_board="$(HRMW --wallet "${wallet_db}" bitcoin ark board --network "${NETWORK}")"
  b_board="$(HRMW --wallet "${rec_db}" bitcoin ark board --network "${NETWORK}")"

  if [[ "${a_fp}" != "${b_fp}" || "${a_tap}" != "${b_tap}" || "${a_board}" != "${b_board}" ]]; then
    echo "[${name}] recovery verification FAILED" >&2
    echo "  original fingerprint: ${a_fp}" >&2
    echo " recovered fingerprint: ${b_fp}" >&2
    echo "  original taproot[0]: ${a_tap}" >&2
    echo " recovered taproot[0]: ${b_tap}" >&2
    echo "  original ARK board : ${a_board}" >&2
    echo " recovered ARK board : ${b_board}" >&2
    return 1
  fi

  cat > "${rec_dir}/verification.txt" <<EOF
status=ok
name=${name}
fingerprint=${a_fp}
taproot_index0=${a_tap}
ark_boarding_address=${a_board}
EOF
  echo "[${name}] recovery verification OK"
}

mkdir -p "${OUT_DIR}"
create_wallet "alice"
create_wallet "bob"
verify_recovery "alice"
verify_recovery "bob"

cat > "${OUT_DIR}/README.txt" <<EOF
Generated by:
  ${REPO_DIR}/scripts/prepare_project_test_wallets.sh

Wallets:
  alice/
  bob/

Recovered verification wallets:
  alice-recovered/
  bob-recovered/

Sensitive files:
  */mnemonic.txt
  */recovery.txt

Keep this directory private and offline when possible.
EOF

echo
echo "Wallet test set ready at: ${OUT_DIR}"
